### ISSUE TITLE
Bingo Progress/Loading Bar

### ISSUE THREAD

**Issue by scriptnull** [scriptnull/bingo#2]
### How the progress/loading bar should look like ?
5x5 table that resembles bingo board. On progress, each box will get stroked off.

### Implementation Details
We have two option here.
1. gif image for loading. 
2. Html+css+js component

Based on discussion, we agreed upon to go with Html+css+js component, because of 
1. Loading and progress can both be shown, whereas in gif only loading can be shown.
2. Html+css+js would accelerate development and might even provide better performance.

### Implementation output
At the end of this task, we will have the following things in our hand.
1. npm package called "bingo-progress-bar"
2. bower package called "bingo-progress-bar"

Anyone will be able to use the progress bar by adding the following tag in his html file.
```html
<link rel="stylesheet" href="styles/bingo-progress-bar.css">
<script src="scripts/bingo-progress-bar.min.js"></script>
```

If a user wants to initialize the progress bar after adding the above two things, he will do 

1.Place a  place holder div, wherever he likes
```html
<div id="progressBar"></div> 
<script>
  var progressBar  = new BingoProgressBar(document.getElementById('progressBar'));
   
  // set 10% progress - 100 is the max value
  progressBar.setProgress(10);
</script>
```

### Implementation Steps.
- [ ] @killerveee creates a repository named "killerveee/bingo-progress-bar"
- [ ] @killerveee and @scriptnull code `bingo-progress-bar` 
- [ ] @killerveee publishes the to npm by doing `npm publish`
- [ ] @killerveee publishes to bower by finding the appropriate steps
