### ISSUE TITLE
Bingo User service.

### ISSUE THREAD

**Issue by scriptnull** [scriptnull/bingo#4]
User table containing normalized user data from login providers like facebook 

### Implementation Steps
- [x] Setup data store - Postgres  ( a script for starting the db everytime we do development  )
- [ ] API service - This is a monolith which will serve all api objects initially. we will move out services one by one when we want.
- [ ] POST /user endpoint

**Comment by scriptnull** [comment]
@argonlaser is working on this service in a new way. So closing this for now.
